// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RESTFulExample.DAL.EF;
using System;

namespace RESTFulExample.DAL.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20180110192645_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RESTFulExample.DAL.Entities.Air", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ArrivalAirport");

                    b.Property<DateTime>("ArrivalDate");

                    b.Property<string>("DepartureAirport");

                    b.Property<DateTime>("DepartureDate");

                    b.Property<string>("Provider");

                    b.Property<int?>("TravellerId");

                    b.HasKey("Id");

                    b.HasIndex("TravellerId");

                    b.ToTable("Airs");
                });

            modelBuilder.Entity("RESTFulExample.DAL.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RESTFulExample.DAL.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Checkin");

                    b.Property<DateTime>("Checkout");

                    b.Property<string>("Name");

                    b.Property<string>("Provider");

                    b.Property<int?>("TravellerId");

                    b.HasKey("Id");

                    b.HasIndex("TravellerId");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("RESTFulExample.DAL.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("event_date");

                    b.Property<string>("exception");

                    b.Property<string>("method_name");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("RESTFulExample.DAL.Entities.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ArrivalDate");

                    b.Property<string>("ArrivalStation");

                    b.Property<DateTime>("DepartureDate");

                    b.Property<string>("DepartureStation");

                    b.Property<string>("Provider");

                    b.Property<int?>("TravellerId");

                    b.HasKey("Id");

                    b.HasIndex("TravellerId");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("RESTFulExample.DAL.Entities.Air", b =>
                {
                    b.HasOne("RESTFulExample.DAL.Entities.Employee", "Traveller")
                        .WithMany()
                        .HasForeignKey("TravellerId");
                });

            modelBuilder.Entity("RESTFulExample.DAL.Entities.Hotel", b =>
                {
                    b.HasOne("RESTFulExample.DAL.Entities.Employee", "Traveller")
                        .WithMany()
                        .HasForeignKey("TravellerId");
                });

            modelBuilder.Entity("RESTFulExample.DAL.Entities.Train", b =>
                {
                    b.HasOne("RESTFulExample.DAL.Entities.Employee", "Traveller")
                        .WithMany()
                        .HasForeignKey("TravellerId");
                });
#pragma warning restore 612, 618
        }
    }
}
