// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RESTFulExample.DAL.EF;
using System;

namespace RESTFulExample.DAL.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20180111181856_1MG")]
    partial class _1MG
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RESTFulExample.DAL.Entities.Air", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("ArrivalDate");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("DepartureDate");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("TravellerId");

                    b.HasKey("Id");

                    b.HasIndex("TravellerId");

                    b.ToTable("Airs");
                });

            modelBuilder.Entity("RESTFulExample.DAL.Entities.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AirId")
                        .HasMaxLength(50);

                    b.Property<int?>("EmployeeId")
                        .IsRequired();

                    b.Property<string>("HotelId")
                        .HasMaxLength(50);

                    b.Property<string>("TrainId")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("AirId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("HotelId");

                    b.HasIndex("TrainId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("RESTFulExample.DAL.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RESTFulExample.DAL.Entities.Hotel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<DateTime>("Checkin");

                    b.Property<DateTime>("Checkout");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Provider")
                        .IsRequired();

                    b.Property<int?>("TravellerId");

                    b.HasKey("Id");

                    b.HasIndex("TravellerId");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("RESTFulExample.DAL.Entities.Train", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<DateTime>("ArrivalDate");

                    b.Property<string>("ArrivalStation")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("DepartureDate");

                    b.Property<string>("DepartureStation")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Provider")
                        .IsRequired();

                    b.Property<int?>("TravellerId");

                    b.HasKey("Id");

                    b.HasIndex("TravellerId");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("RESTFulExample.DAL.Entities.Air", b =>
                {
                    b.HasOne("RESTFulExample.DAL.Entities.Employee", "Traveller")
                        .WithMany()
                        .HasForeignKey("TravellerId");
                });

            modelBuilder.Entity("RESTFulExample.DAL.Entities.Basket", b =>
                {
                    b.HasOne("RESTFulExample.DAL.Entities.Air", "Air")
                        .WithMany()
                        .HasForeignKey("AirId");

                    b.HasOne("RESTFulExample.DAL.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RESTFulExample.DAL.Entities.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId");

                    b.HasOne("RESTFulExample.DAL.Entities.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId");
                });

            modelBuilder.Entity("RESTFulExample.DAL.Entities.Hotel", b =>
                {
                    b.HasOne("RESTFulExample.DAL.Entities.Employee", "Traveller")
                        .WithMany()
                        .HasForeignKey("TravellerId");
                });

            modelBuilder.Entity("RESTFulExample.DAL.Entities.Train", b =>
                {
                    b.HasOne("RESTFulExample.DAL.Entities.Employee", "Traveller")
                        .WithMany()
                        .HasForeignKey("TravellerId");
                });
#pragma warning restore 612, 618
        }
    }
}
